name: njsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan report
      run : |
        cat results.sarif
        curl -X 'POST' \
        'http://35.219.188.29:8080/api/v2/reimport-scan/' \
        -H 'accept: application/json' \
        -H 'Authorization: Token 4077a2c38348314c96b25b912271127a5d0589b4' \
        -H 'Content-Type: multipart/form-data' \
        -F 'test=1' \
        -F '[email protected];type=application/json' \
        -F file=@"results.sarif" \
        -F 'scan_type=SARIF' \
        -F 'tags=test'

  npmAudit:
    runs-on: ubuntu-latest
    name: npmAudit library scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: npmAudit scan
      run : |
        curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install -g npm@6.14.18
    - name: Upload npmAudit report
      run : |
        npm i --package-lock-only
        npm audit --json >> npm_result.json | true
        cat npm_result.json
        curl -X 'POST' \
        'http://35.219.188.29:8080/api/v2/reimport-scan/' \
        -H 'accept: application/json' \
        -H 'Authorization: Token 4077a2c38348314c96b25b912271127a5d0589b4' \
        -H 'Content-Type: multipart/form-data' \
        -F 'test=2' \
